# Generated by Django 5.0.4 on 2024-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
