# Generated by Django 5.0.4 on 2024-07-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_post_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(default='avatar.png', upload_to='profile_pics'),
        ),
    ]
