# Generated by Django 5.0.4 on 2024-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_post_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/avatar.png', upload_to='profile_pics'),
        ),
    ]
